# Generated by Django 6.0.5 on 2026-05-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255)),
                ('original', models.FileField(upload_to='videos/originals')),
                ('traite', models.FileField(blank=True, null=True, upload_to='videos/traite')),
                ('status', models.CharField(choices=[('EN ATTENTE', 'en attente'), ('EN COURS DE TRAITEMENT', 'en cours de traitement'), ('TERMINE', 'termine'), ('ECHOUE', 'echoue')], default='EN ATTENTE', max_length=22)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
