# Generated by Django 6.0.5 on 2026-06-16 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='project',
        ),
        migrations.RemoveField(
            model_name='videoclip',
            name='project',
        ),
        migrations.DeleteModel(
            name='VideoProject',
        ),
    ]
