# Generated by Django 6.0.5 on 2026-05-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_exportjob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exportjob',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='exportjob',
            old_name='error_msg',
            new_name='mes_erreur',
        ),
        migrations.RenameField(
            model_name='exportjob',
            old_name='quality',
            new_name='qualite',
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'en attente'), ('EN COURS DE TRAITEMENT', 'en cours de traitement'), ('TERMINE', 'termine'), ('ECHOUE', 'echoue')], default='EN ATTENTE', max_length=22),
        ),
    ]
