# Generated by Django 6.0.5 on 2026-06-02 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_video_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeClippingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('NORMALISEE', 'normalisee'), ('CLIPEE', 'clipee'), ('PORTRAIT', 'portrait'), ('SOUS-TITREE', 'sous-titree'), ('THUMBNAIL', 'thumbnail'), ('COMPRESSEE', 'compressee')], default='EN ATTENTE', max_length=22)),
                ('output_path', models.TextField(blank=True, null=True)),
                ('mes_erreur', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.video')),
            ],
        ),
    ]
