# Generated by Django 6.0.5 on 2026-06-03 12:34

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_realtimeclippingjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtimeclippingjob',
            name='output_path',
        ),
        migrations.AddField(
            model_name='video',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='videos/audio'),
        ),
        migrations.AlterField(
            model_name='realtimeclippingjob',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'en attente'), ('NORMALISEE', 'normalisee'), ('SOUS-TITREE', 'sous-titree'), ('CLIPEE', 'clipee'), ('PORTRAIT', 'portrait'), ('THUMBNAIL', 'thumbnail'), ('COMPRESSEE', 'compressee'), ('TERMINE', 'termine'), ('ECHOUE', 'echoue')], default='EN ATTENTE', max_length=22),
        ),
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip', models.FileField(upload_to=api.models.clip_upload_path)),
                ('debut', models.DurationField()),
                ('fin', models.DurationField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='api.realtimeclippingjob')),
            ],
        ),
    ]
