# Generated by Django 6.0.5 on 2026-06-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_realtimeclippingjob_output_path_video_audio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimeclippingjob',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'en attente'), ('NORMALISEE', 'normalisee'), ('SOUS-TITREE', 'sous-titree'), ('SON EXTRAIT', 'son extrait'), ('CLIPEE', 'clipee'), ('PORTRAIT', 'portrait'), ('THUMBNAIL', 'thumbnail'), ('COMPRESSEE', 'compressee'), ('TERMINE', 'termine'), ('ECHOUE', 'echoue')], default='EN ATTENTE', max_length=22),
        ),
    ]
