# Generated by Django 6.0.5 on 2026-06-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_realtimeclippingjob_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtimeclippingjob',
            name='task_id',
        ),
    ]
