# Generated by Django 6.0.5 on 2026-06-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_realtimeclippingjob_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoclip',
            name='debut',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='fin',
            field=models.TimeField(),
        ),
    ]
