# Generated by Django 6.0.5 on 2026-06-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_videoclip_debut_alter_videoclip_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoclip',
            name='debut',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='videoclip',
            name='fin',
            field=models.TimeField(),
        ),
    ]
