# Generated by Django 6.0.5 on 2026-06-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_videoclip_debut_alter_videoclip_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoclip',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'en attente'), ('EN COURS DE TRAITEMENT', 'en cours de traitement'), ('TERMINE', 'termine'), ('ECHOUE', 'echoue')], default='EN ATTENTE', max_length=22),
        ),
    ]
