# Generated by Django 6.0.5 on 2026-06-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_videoclip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimeclippingjob',
            name='status',
            field=models.CharField(choices=[('EN ATTENTE', 'en attente'), ('SON EXTRAIT', 'son extrait'), ('CLIPEE', 'clipee'), ('PORTRAIT', 'portrait'), ('SON AMELIORE', 'son ameliore'), ('THUMBNAIL', 'thumbnail'), ('COMPRESSEE', 'compressee'), ('TERMINE', 'termine'), ('ECHOUE', 'echoue')], default='EN ATTENTE', max_length=22),
        ),
    ]
