# Generated by Claude for ClipExportJob model

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_realtimeclippingjob_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('fmt', models.CharField(max_length=10)),
                ('qualite', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('EN ATTENTE', 'en attente'), ('EN COURS DE TRAITEMENT', 'en cours de traitement'), ('TERMINE', 'termine'), ('ECHOUE', 'echoue')], default='EN ATTENTE', max_length=22)),
                ('output_path', models.TextField(blank=True, null=True)),
                ('mes_erreur', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='api.videoclip')),
            ],
        ),
    ]
